<?php

namespace Modules\Mosque\Database\Seeders;
use Illuminate\Database\Seeder;

class MosquesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mosques')->delete();
        
        \DB::table('mosques')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Sapporo Masjid',
                'image' => 'mosques/samples/aarTsK26F0A5NPlbZ29r.jpg',
                'description' => NULL,
                'address' => 'Kita 14 jo Nishi 3 Chome 1-10,Kitaku,Sapporo,Hokkaido-Japan',
                'website' => 'http://www.sapporomasjid.com',
                'prefectures' => 'Hokkaido',
                'city' => 'Sapporo-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:29:39',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Masjid Al-Noor',
                'image' => 'mosques/samples/lMkMDnEcuhYyhhlCeXMt.jpg',
                'description' => NULL,
                'address' => 'Hokkaido Otaru-shi Inaho 5-4-27',
                'website' => 'http://www.noormasjid.com',
                'prefectures' => 'Hokkaido',
                'city' => 'Otaru-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:31:07',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Muroran Mosque',
                'image' => 'mosques/samples/GlZbJfPetLrKdRvUgXRh.JPG',
                'description' => NULL,
                'address' => '5-18-6-1F Takasago-cho, Muroran-shi, Hokkaido',
                'website' => NULL,
                'prefectures' => 'Hokkaido',
                'city' => 'Muroran-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:31:53',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Chitose Outlet Mall RERA',
                'image' => '',
                'description' => '',
                'address' => '1-2-1 , Kashiwadai Minami, Shitose-shi, Hokkaido',
                'website' => 'http://www.outlet-rera.com/english/',
                'prefectures' => 'Hokkaido',
                'city' => 'Shitose-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Morioka Masjid',
                'image' => 'mosques/samples/HFTEHmljpXznkHgtNECZ.jpg',
                'description' => NULL,
                'address' => '2-22 Abetate-cho, Morioka-shi, Iwate',
                'website' => 'http://moriokamuslim.blogspot.jp/',
                'prefectures' => 'Iwate',
                'city' => 'Morioka-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:32:46',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Iwaki Masjid',
                'image' => 'mosques/samples/TOqYrm8NN50NPrKF0zrE.jpg',
                'description' => NULL,
                'address' => '176-1 Miyanoshita Shimokawa , Izumi-cho , Iwaki-shi , Fukushima',
                'website' => NULL,
                'prefectures' => 'Fukushima',
                'city' => 'Iwaki-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:35:24',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Islamic Cultural Centre of Sendai',
                'image' => 'mosques/samples/PyDuEVVNzpfyeDRLuba5.jpg',
                'description' => NULL,
                'address' => '7-24, hachiman 7-chome, Aoba-ku, Sendai, Miyagi, Japan.',
                'website' => 'http://iccsendai.org/web/en/',
                'prefectures' => 'Miyagi',
                'city' => 'sendai-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:36:03',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Tokyo Camii',
                'image' => 'mosques/samples/1wLMbxcYS4TY3XFaOT2U.jpg',
                'description' => NULL,
                'address' => '1-19 Oyama-cho, Shibuya-ku, Tokyo 151-0065, JAPAN',
                'website' => 'http://tokyocamii.org/',
                'prefectures' => 'Tokyo',
                'city' => 'Shibuya-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:36:38',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'As-Salaam Masjid',
                'image' => 'mosques/samples/REPbV3wN4RH3FSgcf5fs.jpg',
                'description' => NULL,
                'address' => '4-6-7 Taito Taito-ku Tokyo 110-0016',
                'website' => 'http://assalaamfoundation.org/',
                'prefectures' => 'Tokyo',
                'city' => 'Taito-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:37:05',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Masjid Nusantara',
                'image' => 'mosques/samples/m9oILhhQjbWDsD5C9nQ3.jpeg',
                'description' => NULL,
                'address' => '101-0041 Tokyo, Chiyoda-ku, Kanda Sudacho, 2−17',
                'website' => NULL,
                'prefectures' => 'Tokyo',
                'city' => 'Chiyoda-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:37:55',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Otsuka Masjid',
                'image' => 'mosques/samples/isfroxghdy4u6YyFoeE3.jpg',
                'description' => NULL,
                'address' => '3-42-7 Minami Otsuka, Toshima-ku, Tokyo',
                'website' => 'http://www.islam.or.jp',
                'prefectures' => 'Tokyo',
                'city' => 'Toshima-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:38:39',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Kamata Masjid',
                'image' => 'mosques/samples/SV6KHMg6MstijYs0neMg.jpg',
                'description' => NULL,
                'address' => '5-1-2 Kamata, Ota-ku, Tokyo',
                'website' => 'http://kamatamasjid.com',
                'prefectures' => 'Tokyo',
                'city' => 'Ota-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:39:09',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Al-Tawheed Mosque',
                'image' => 'mosques/samples/hPI4HdmZf0STsSxhnKyF.jpg',
                'description' => NULL,
                'address' => '36-6 Hiraoka-cho Hachioji-shi Tokyo',
                'website' => 'http://www.geocities.jp/masjid_al_tawheed/',
                'prefectures' => 'Tokyo',
                'city' => 'Hachioji-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:40:07',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Hira Masjid',
                'image' => 'mosques/samples/PgPdJL6EewvDdXfBWgVi.jpeg',
                'description' => NULL,
                'address' => '3-3-19 Gyotoku Ekimae, Ichikawa-shi, Chiba',
                'website' => 'http://www.hiramasjid.org/',
                'prefectures' => 'Chiba',
                'city' => 'Ishikawa-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:40:37',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Ja’me Masjid Yokohama',
                'image' => 'mosques/samples/ELD7ikFUIVvWXrdAETrk.jpeg',
                'description' => NULL,
                'address' => '1-31-13 Hayabuchi, Tsuzuki-ku, Yokohama-city, Kanagawa',
                'website' => 'http://www.masjid-yokohama.jp',
                'prefectures' => 'Kanagawa',
                'city' => 'Yokohama-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:41:38',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Ebina Mosque',
                'image' => 'mosques/samples/TxAx9JgMKyqnch1aL6F3.jpg',
                'description' => NULL,
                'address' => '3-12-1 Kamigo, Ebina-shi, Kanagawa',
                'website' => 'https://www.facebook.com/pages/Ebina-Mosque/352827714734696',
                'prefectures' => 'Kanagawa',
                'city' => 'Ebina-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:42:52',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Bilal Mosque',
                'image' => 'mosques/samples/W6jX70PYXn1xBXuC6shj.jpg',
                'description' => NULL,
                'address' => '6830-4 Minamijyo, Sakaki-machi, Hanishina-gun, Nagano',
                'website' => NULL,
                'prefectures' => 'Nagano',
                'city' => 'Hanishina-gun',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:43:40',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Fuji Masjid',
                'image' => 'mosques/samples/Su0Ml4A5SmBOJdIsq6cX.jpg',
                'description' => NULL,
                'address' => '2561-29 Nakazato, Fuji-shi, Shizuoka',
                'website' => NULL,
                'prefectures' => 'Shizuoka',
                'city' => 'Fuji-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:44:01',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Mohammadi Mosque',
                'image' => 'mosques/samples/erZtpVo7feAPXwB98tvK.jpg',
                'description' => NULL,
                'address' => '161-2 Terawaki cho, Minami-ku, Hamamatsu-shi, Shizuoka',
                'website' => 'http://www.hamamatsumosque.com',
                'prefectures' => 'Shizuoka',
                'city' => 'Hamamatu-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:45:09',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Nagoya Mosque',
                'image' => 'mosques/samples/03NFQAnrxdq3mGnYpuMr.png',
                'description' => NULL,
                'address' => '2-26-7 Honjindori, Nakamura-ku, Nagoya, Aichi',
                'website' => 'http://en.nagoyamosque.com',
                'prefectures' => 'Aichi',
                'city' => 'Nagoya-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:45:44',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Kyoto Masjid',
                'image' => 'mosques/samples/ZrxsOrVsZNxaTwWkrHZa.jpg',
                'description' => NULL,
                'address' => 'Miyagaki-cho92, Kamigyo-ku Kawaramachi, Kyoto-shi, Kyoto',
                'website' => 'http://www.islamjapan.net/ibc/index.html',
                'prefectures' => 'Kyoto',
                'city' => 'Kyoto-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:46:09',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Osaka Masjid',
                'image' => 'mosques/samples/pegq8sqbCZTjU7VJTm0G.jpg',
                'description' => NULL,
                'address' => '4-12-16 Owada Nishi Yodogawa-ku Osaka',
                'website' => 'http://osakamasjid.info',
                'prefectures' => 'Osaka',
                'city' => 'Yodogawa-ku',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:46:40',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Osaka Ibaraki Mosque',
                'image' => '',
                'description' => '',
                'address' => '4-6-13, Toyokawa, Ibaraki City , Osaka',
                'website' => 'http://osakamosque.org',
                'prefectures' => 'Osaka',
                'city' => 'Ibaraki-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Kobe Muslim Mosque',
                'image' => '',
                'description' => '',
                'address' => '2-25-14 Nakayamate Dori, Chuo-ku, Kobe-shi, Hyogo',
                'website' => 'http://kobe-muslim-mosque.com',
                'prefectures' => 'Hyogo',
                'city' => 'kobe-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Okayama Islamic Center',
                'image' => '',
                'description' => '',
                'address' => '2-1-7 Tsushima Higashi, Kita-ku, Okayama-shi, Okayama',
                'website' => 'https://www.facebook.com/pages/Okayama-Islamic-Centre/123860261139298',
                'prefectures' => 'Okayama',
                'city' => 'Okayama-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Higashihiroshima Masjid',
                'image' => '',
                'description' => '',
                'address' => '2786-1, Taguchi, Saijyou-cho, Higashihiroshima-shi, Hiroshima',
                'website' => 'https://www.hiroshima-icc.org',
                'prefectures' => 'Hiroshima',
                'city' => 'Higashihiroshima-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Niihama Masjid',
                'image' => '',
                'description' => '',
                'address' => '2-2-43 Ikku-cho, Niihama-shi, Ehime',
                'website' => 'https://www.facebook.com/pages/新居浜マスジド/168623866678430',
                'prefectures' => 'Ehime',
                'city' => 'Niihama-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Fukuoka Masjid',
                'image' => '',
                'description' => '',
                'address' => '3-2-18 Hakozaki , Higashi-ku, Fukuoka-shi, Fukuoka',
                'website' => 'http://www.fukuokamasjid.org',
                'prefectures' => 'Fukuoka',
                'city' => 'Fukuoka-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Beppu Masjid',
                'image' => '',
                'description' => '',
                'address' => '10-19 Wakakusa-cho, Beppu-shi, Oita',
                'website' => '',
                'prefectures' => 'Oita',
                'city' => 'Beppu-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Kumamoto Islamic Center',
                'image' => '',
                'description' => '',
                'address' => '5-5-2, Kurokammi, chuou-ku, Kumamoto-shi, Kumamoto',
                'website' => 'http://www.kicjapan.com/',
                'prefectures' => 'Kumamoto',
                'city' => 'Kumamoto-shi',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Kagoshima Masjid',
                'image' => 'mosques/samples/EcSkxyBnEV5J8U12wAWa.jpg',
                'description' => NULL,
                'address' => '84-21, Masago-cho, Kagoshima',
                'website' => 'http://www.sicc-kagoshima.org',
                'prefectures' => 'Kagoshima',
                'city' => 'Masago-cho',
                'country_id' => 107,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-12-13 01:14:47',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}